// Code generated by reactGen. DO NOT EDIT.

package sharebutton

import "myitcv.io/react"

type ShareItemsBtnElem struct {
	react.Element
}

func (s ShareItemsBtnDef) ShouldComponentUpdateIntf(nextProps react.Props, prevState, nextState react.State) bool {
	res := false

	{
		res = s.Props() != nextProps.(ShareItemsBtnProps) || res
	}
	return res
}

func buildShareItemsBtn(cd react.ComponentDef) react.Component {
	return ShareItemsBtnDef{ComponentDef: cd}
}

func buildShareItemsBtnElem(props ShareItemsBtnProps, children ...react.Element) *ShareItemsBtnElem {
	return &ShareItemsBtnElem{
		Element: react.CreateElement(buildShareItemsBtn, props, children...),
	}
}

// IsProps is an auto-generated definition so that ShareItemsBtnProps implements
// the myitcv.io/react.Props interface.
func (s ShareItemsBtnProps) IsProps() {}

// Props is an auto-generated proxy to the current props of ShareItemsBtn
func (s ShareItemsBtnDef) Props() ShareItemsBtnProps {
	uprops := s.ComponentDef.Props()
	return uprops.(ShareItemsBtnProps)
}

func (s ShareItemsBtnProps) EqualsIntf(val react.Props) bool {
	return s == val.(ShareItemsBtnProps)
}

var _ react.Props = ShareItemsBtnProps{}
