linters:
  enable:
    - errorlint
    - gofmt
    - ineffassign
    - misspell
    - noctx
    - prealloc
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign

  disable:
    - bodyclose
    - dupl
    - errcheck
    - goconst
    - gocritic
    - interfacer
    - unparam

issues:
  exclude:
    - "`?encodeFixed(32|64)Pb`? is unused"

# vim: set et shiftwidth=2:
#
