#!/usr/bin/perl

use strict;
use FindBin qw($Bin);

system("$Bin/build.pl", "camput") and die "failed to build camput";

# Respected by camli/osutil:
$ENV{"CAMLI_CONFIG_DIR"} = "$Bin/config/dev-client-dir";

# Respected by env expansions in config/dev-client-dir/config
$ENV{"CAMLI_SECRET_RING"} = "$Bin/lib/go/camli/jsonsign/testdata/test-secring.gpg";
$ENV{"CAMLI_DEV_KEYBLOBS"} = "$Bin/config/dev-client-dir/keyblobs";

system("$Bin/clients/go/camput/camput",
       "--verbose",
       "--blobserver=http://localhost:3179/bs",
       "--password=pass3179",
       @ARGV);
