#!/usr/bin/perl

use strict;
use FindBin qw($Bin);
use Getopt::Long;
require "$Bin/misc/devlib.pl";

my $camsync = build_bin("./cmd/camsync");
exec($camsync, "--verbose", "--src=http://localhost:3179/bs", "--srcpassword=pass3179", @ARGV);
die "Failed to exec camsync.";

