#!/usr/bin/perl

use strict;
use FindBin qw($Bin);
use Getopt::Long;
require "$Bin/misc/devlib.pl";

my $tool = build_bin("./cmd/camtool");

# Copy of dev-camget's settings. See comments there.
$ENV{"CAMLI_CONFIG_DIR"} = "$Bin/config/dev-client-dir";
$ENV{"CAMLI_SECRET_RING"} = "$Bin/pkg/jsonsign/testdata/test-secring.gpg";
$ENV{"CAMLI_KEYID"} = "26F5ABDA";
$ENV{"CAMLI_DEV_KEYBLOBS"} = "$Bin/config/dev-client-dir/keyblobs";
$ENV{"CAMLI_AUTH"} = "userpass:camlistore:pass3179";

exec($tool, @ARGV);
die "Failed to exec camtool.";

