all:
	make -C blobref install
	make -C clientconfig install
	make -C http install
	make -C jsonsign install

clean:
	make -C blobref clean
	make -C clientconfig clean
	make -C http clean
	make -C jsonsign clean

