all:
	make -C ext/openpgp install
	make -C blobref install
	make -C schema install
	make -C clientconfig install
	make -C http install
	make -C jsonsign install

clean:
	make -C ext/openpgp clean
	make -C schema clean
	make -C blobref clean
	make -C clientconfig clean
	make -C http clean
	make -C jsonsign clean

