all:
	make -C auth install
	make -C http_util install
	make -C blobref install
	make -C webserver install
	make -C openpgp install
	make -C blobserver install
	make -C sigserver install

clean:
	make -C auth clean
	make -C http_util clean
	make -C blobref clean
	make -C webserver clean
	make -C openpgp clean
	make -C blobserver clean
	make -C sigserver clean
