#!/bin/sh
# Copyright (c) 2010 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# git-cl -- a git-command for integrating reviews on Rietveld
# Copyright (C) 2008 Evan Martin <martine@danga.com>

base_dir=$(dirname "$0")

#don't want this in here for now
#"$base_dir"/update_depot_tools
"$base_dir"/git_cl.py "$@"
