# Copyright 2015 The Camlistore Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FROM debian:wheezy

ENV DEBIAN_FRONTEND noninteractive

ADD build.sh /scripts/build.sh
RUN /scripts/build.sh
