// Code generated by reactGen. DO NOT EDIT.

package aboutdialog

import "myitcv.io/react"

type AboutMenuItemElem struct {
	react.Element
}

func (a AboutMenuItemDef) ShouldComponentUpdateIntf(nextProps react.Props, prevState, nextState react.State) bool {
	res := false

	{
		res = a.Props() != nextProps.(AboutMenuItemProps) || res
	}
	return res
}

func buildAboutMenuItem(cd react.ComponentDef) react.Component {
	return AboutMenuItemDef{ComponentDef: cd}
}

func buildAboutMenuItemElem(props AboutMenuItemProps, children ...react.Element) *AboutMenuItemElem {
	return &AboutMenuItemElem{
		Element: react.CreateElement(buildAboutMenuItem, props, children...),
	}
}

// IsProps is an auto-generated definition so that AboutMenuItemProps implements
// the myitcv.io/react.Props interface.
func (a AboutMenuItemProps) IsProps() {}

// Props is an auto-generated proxy to the current props of AboutMenuItem
func (a AboutMenuItemDef) Props() AboutMenuItemProps {
	uprops := a.ComponentDef.Props()
	return uprops.(AboutMenuItemProps)
}

func (a AboutMenuItemProps) EqualsIntf(val react.Props) bool {
	return a == val.(AboutMenuItemProps)
}

var _ react.Props = AboutMenuItemProps{}
