#!/bin/sh

set -e
Bin=$(dirname $( readlink -f $0))

export CAMLI_PASSWORD=`cat $HOME/.config/camlistore/camorg-blobserver.pass`
export CAMLI_ROOT=$Bin/../blobserver-example/root

cd $Bin/../..
go run make.go \
	-embed_static=false \
	-targets=camlistore.org/server/camlistored && \
./bin/camlistored \
	-configfile=$Bin/../blobserver-example/example-blobserver-config.json \
	-listen=:3179 "$@"

