#!/bin/sh

set -e
Bin=$(dirname $( readlink -f $0))

export CAMLI_PASSWORD=`cat $HOME/.camli/camorg-blobserver.pass`
export CAMLI_ROOT=$Bin/../blobserver-example/root

$Bin/../../build.pl server/go/camlistored && \
   $Bin/../../server/go/camlistored/camlistored \
       -configfile=$Bin/../blobserver-example/example-blobserver-config.json \
       -listen=:3179 "$@"

