include $(GOROOT)/src/Make.inc

TARG=camlistored
GOFILES=\
	camlistored.go\
	blobref.go\
	enumerate.go\
	get.go\
	preupload.go\
	temp_testing.go\
	range.go\
	upload.go\

include $(GOROOT)/src/Make.cmd
