include $(GOROOT)/src/Make.inc

TARG=camlistored
GOFILES=\
	camlistored.go\
	enumerate.go\
	get.go\
	interface.go\
	localdisk.go\
	partitions.go\
	preupload.go\
	range.go\
	remove.go\
	temp_testing.go\
	upload.go\
	util.go\

include $(GOROOT)/src/Make.cmd
