#!/bin/sh

outfile=zsearch.go
cat >$outfile <<EOF
// generated by gensearchtypes.sh; DO NOT EDIT

/*
Copyright 2016 The Camlistore Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"net/url"
	"time"

	"camlistore.org/pkg/blob"
	"camlistore.org/pkg/types/camtypes"
)

// Duplicating the search pkg types in here - since we only use them for json
// decoding - , instead of importing them through the search package, which would
// bring in more dependencies, and hence a larger js file.
// To give an idea, the generated publisher.js is ~3.5MB, whereas if we instead import
// camlistore.org/pkg/search to use its types instead of the ones below, we grow to
// ~5.7MB.

EOF

go doc camlistore.org/pkg/search.SearchResult | sed '/^func.*/d' | sed '/^    .*/d' >> $outfile
go doc camlistore.org/pkg/search.SearchResultBlob | sed '/^func.*/d' | sed '/^    .*/d' >> $outfile
go doc camlistore.org/pkg/search.DescribeResponse | sed '/^func.*/d' | sed '/^    .*/d' >> $outfile
go doc camlistore.org/pkg/search.MetaMap | sed '/^func.*/d' | sed '/^    .*/d' >> $outfile
# stripping DescribeRequest from DescribeBlob because it would pull a lot more of search pkg in
go doc camlistore.org/pkg/search.DescribedBlob | sed '/^	Request\ \*DescribeRequest.*/d' | sed '/^func.*/d' | sed '/^    .*/d' >> $outfile
go doc camlistore.org/pkg/search.DescribedPermanode | sed '/^func.*/d' | sed '/^    .*/d' >> $outfile
gofmt -w $outfile
