all:
	make -C armor
	make -C error
	make -C packet

install:
	make -C armor install
	make -C error install
	make -C packet install

clean:
	make -C armor clean
	make -C error clean
	make -C packet clean
