#!/bin/sh
# Copyright 2018 The Perkeep Authors.
# Licensed under the Apache License, Version 2.0

### This script will execute ONLY when package upgraded.
### Actions before package upgraded.
### ex. backup user settings for package upgrade.

# TODO(mpl): figure out if anything to do for upgrades

exit 0
