#!/bin/sh
# Copyright 2018 The Perkeep Authors.
# Licensed under the Apache License, Version 2.0

### This script will be executed when package uninstalled and upgraded.
### Actions before package uninstalled
### ex. backup package data.

exit 0
